# Generated by Django 4.1.5 on 2023-01-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('image', models.ImageField(upload_to='images/charts')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Все изображения',
            },
        ),
    ]
