# Generated by Django 4.1.5 on 2023-01-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_analytics_web_site', '0004_vacancies1csalaryyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountVacancies1С',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('value', models.PositiveIntegerField(verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Строку',
                'verbose_name_plural': 'Динамика количества вакансий по годам для 1С-разработчика',
            },
        ),
        migrations.CreateModel(
            name='AmountVacanciesAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('value', models.PositiveIntegerField(verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Строку',
                'verbose_name_plural': 'Динамика количества вакансий по годам для всех профессий',
            },
        ),
    ]
