# Generated by Django 4.1.5 on 2023-01-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_analytics_web_site', '0005_amountvacancies1с_amountvacanciesall'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountvacancies1с',
            name='title',
            field=models.CharField(default=0, max_length=128, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amountvacanciesall',
            name='title',
            field=models.CharField(default=1, max_length=128, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amountvacancies1с',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Число вакансий'),
        ),
    ]
