# Generated by Django 4.1.5 on 2023-01-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_analytics_web_site', '0006_amountvacancies1с_title_amountvacanciesall_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmountVacanciesAll',
        ),
    ]
