# Generated by Django 4.1.5 on 2023-01-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_analytics_web_site', '0008_amountvacanciesall'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Информация')),
                ('image', models.ImageField(upload_to='images/charts')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'О профессии',
            },
        ),
    ]
