# Generated by Django 4.1.5 on 2023-01-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_analytics_web_site', '0010_citychartssalaryyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityTableSalaryYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128, verbose_name='Название')),
                ('curren', models.CharField(max_length=8, verbose_name='Валюта')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Строку',
                'verbose_name_plural': 'Графики зарплаты в городах по годам',
            },
        ),
        migrations.DeleteModel(
            name='CityChartsSalaryYear',
        ),
    ]
