# Generated by Django 4.1.5 on 2023-01-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_analytics_web_site', '0011_citytablesalaryyear_delete_citychartssalaryyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsTableYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=128, verbose_name='Название')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Строку',
                'verbose_name_plural': 'Топ 10-навыков по годам',
            },
        ),
        migrations.AlterModelOptions(
            name='citytablesalaryyear',
            options={'verbose_name': 'Строку', 'verbose_name_plural': 'Таблицы зарплаты в городах по годам'},
        ),
    ]
