# Generated by Django 4.1.5 on 2023-01-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_analytics_web_site', '0012_skillstableyear_alter_citytablesalaryyear_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillstableyear',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во вакансий с этим навыком'),
            preserve_default=False,
        ),
    ]
